### PR TITLE
feat: add style and slot types

### LINKED ISSUE #12: `style` works, but the ts type reports an error
[Test link](https://github.com/ayangweb/stencil-test/commit/1d030e3344b616401c12490d24c92776e6370b80)

image

image

### LINKED ISSUE #13: bug: problem with slot type error reporting!
Passing a custom component as a slot to another component causes ts to report an error because it has no type!

image

### PR DESCRIPTION
**Pull request by ayangweb**
- fixes #12 
- fixes #13

### CODE REVIEW

**Comment by ayangweb** [comment]
```shell
github:arthur-fontaine/stencil-solid-output-target#pull/14/head
```

After my testing, the `style` and `slot` attributes don't report errors anymore!

**Comment by ayangweb** [comment]
@arthur-fontaine Take the time to test it out and then merge all the pr's and deploy it! I can't wait to use it!

**Review by arthur-fontaine — CHANGES_REQUESTED** [review]
Thank you for your PR. Can you reformat the code to match the existing style (indent, quotes, etc.)?

**Comment by ayangweb** [comment]
> Thank you for your PR. Can you reformat the code to match the existing style (indent, quotes, etc.)?

No problem, I'm outside now, I'll change it later

**Comment by ayangweb** [comment]
> Thank you for your PR. Can you reformat the code to match the existing style (indent, quotes, etc.)?

I'm not sure which way you are using code formatting? I'm using `prettier` I switched will the js save function that comes with it and that didn't work either!

Furthermore, I'll send you the code and you can add it!

```tsx
export interface ComponentExpansionType {
  style?: JSX.CSSProperties
  slot?: string
}

Component<PropType & JSX.DOMAttributes<ElementType> & ComponentExpansionType>
```

image

**Pull request merged**
